FROM eu.gcr.io/gitpod-core-dev/build/registry-facade:commit-6c883c70ab109a6d259e331e0d72a411b10cfa01

COPY ["test.crt", "/usr/local/share/ca-certificates"]

RUN ["/bin/bash","-lc","update-ca-certificates"]