FROM eu.gcr.io/gitpod-core-dev/build/registry-facade:commit-6c883c70ab109a6d259e331e0d72a411b10cfa01
#FROM registry.cn-hangzhou.aliyuncs.com/1992w/gitpod-registry-facade:commit-6c883c70ab109a6d259e331e0d72a411b10cfa01

USER root

RUN apk update \
        && apk upgrade \
        && apk add --no-cache ca-certificates bash 
RUN mkdir -p /usr/local/share/ca-certificates/
COPY ["rootCA.crt", "/usr/local/share/ca-certificates"]
RUN ["/bin/bash", "-lc", "update-ca-certificates"]