FROM eu.gcr.io/gitpod-core-dev/build/ca-updater:commit-313e75e99d5db6f5ac4eb71ecc25b8807fdd8366

COPY ["test.crt", "/usr/local/share/ca-certificates/"]
RUN ["/bin/bash","-lc","update-ca-certificates"]